# -*- coding: utf-8 -*-
"""
organize_photos.py: Reorganize photos and videos into a folder structure that
makes sense, as opposed to the way Google Photos downloads are received via
the Google Takeout service.

Assumes the unzipped Google Takeout folders are all in the same directory, with
no other files within the directory. These folders should retain their original
automatically-generated names, and no other changes should be made to their
structure before running organize_photos.py.

The script will first determine the list of unique folder names generated by
Google Photos that reside in the Takeout folders (i.e. Photos 2017, Trip to
Moab, etc.). It will then create empty directories in the original working
directory with those names. Finally, it will iterate through the Takeout
folders and move the files to the new named directories.


Created on Wed Apr 27 12:15:08 2022

@author: Ryan.Larson
"""

import os

def get_folder_names(workingDirectory):
    rootdir = workingDirectory
    
    all_directories = []
    
    for file in os.listdir(rootdir):
        d = os.path.join(rootdir, file)
        if os.path.isdir(d):
            basename = os.path.basename(d)
            all_directories.append(basename)
            
    print(all_directories)
    return all_directories

if __name__ == "__main__":
    workingDirectory = "C:\\Users\\Ryan.Larson.ROCKWELLINC\\OneDrive - Rockwell Inc\\Desktop\\test_directory"
    all_directories = get_folder_names(workingDirectory)